# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Birkhoff-Fan clustering
#'
#' This function computes a solution sequence of the Birkhoff-Fan clustering. 
#' It takes a symmetric matrix \code{S} as input and returns a object 
#' containing a list of normalized clustering matrices estimated by 
#' Birkhoff-Fan clustering over a sequence of the number of clusters.
#'
#' @param S            input pairwise similarity matrix
#'                     (assumed to be symmetric)
#' @param nclust       a vector of the number of clusters
#' @param maxiter      max number of iterations for each solution
#' @param tolerance    convergence threshold 
#' @param admm_penalty penalty parameter of ADMM algorithm
#' @param verbose      level of verbosity
#'
#' @return An S3 object of class \code{bfcluster} which is a list with 
#'         the following components:
#'  \item{nclust}{a vector containing the number of clusters of each estimate}
#'  \item{clustmat}{a list containing the normalized clustering matrix 
#'                  estimates}
#'  \item{maxval}{a vector of optimal objective function values 
#'                for each value of the number of clusters}
#'  \item{niter}{a vector containing the number of ADMM iterations for each 
#'               estimate}
#' @export
bfcluster <- function(S, nclust = as.integer( c()), maxiter = 100L, tolerance = 1e-2, admm_penalty = 100, verbose = 0L) {
    .Call('bfcluster_bfcluster', PACKAGE = 'bfcluster', S, nclust, maxiter, tolerance, admm_penalty, verbose)
}

